import { toPng } from 'html-to-image';
import { jsPDF } from 'jspdf';

/**
 * Downloads an invoice as PDF using html-to-image + jsPDF.
 * This approach takes a visual snapshot (like a screenshot) and embeds it in a PDF.
 * It avoids all CSS parsing issues with modern color functions.
 * 
 * @param invoiceElement - The HTML element to convert to PDF
 * @param invoiceNumber - Optional invoice number for filename
 * @param isFreePlan - Whether the user is on a free plan (adds watermark)
 */
export const downloadInvoiceAsPDF = async (
  invoiceElement: HTMLElement,
  invoiceNumber?: string,
  isFreePlan: boolean = false
): Promise<void> => {
  if (!invoiceElement) {
    throw new Error('Invoice element is required for PDF generation');
  }

  try {
    // Generate filename
    const filename = invoiceNumber 
      ? `invoice-${invoiceNumber}.pdf` 
      : `invoice-${new Date().toISOString().split('T')[0]}.pdf`;

    // Get the dimensions of the invoice element
    const width = invoiceElement.offsetWidth;
    const height = invoiceElement.offsetHeight;

    // Convert HTML to PNG image with high quality
    const dataUrl = await toPng(invoiceElement, {
      quality: 1.0,
      pixelRatio: 2, // Higher resolution for better quality
      cacheBust: true,
      backgroundColor: '#ffffff',
    });

    // Calculate PDF dimensions (A4 size in mm)
    const pdfWidth = 210; // A4 width in mm
    const pdfHeight = (height * pdfWidth) / width; // Maintain aspect ratio

    // Create PDF with appropriate orientation
    const orientation = pdfHeight > pdfWidth ? 'portrait' : 'landscape';
    const pdf = new jsPDF({
      orientation,
      unit: 'mm',
      format: 'a4',
    });

    pdf.addImage(dataUrl, 'PNG', 0, 0, pdfWidth, pdfHeight);

    if (isFreePlan) {
      pdf.setTextColor(200, 200, 200);
      pdf.setFontSize(50);
      pdf.setFont('helvetica', 'bold');
      
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      
      const watermarkText = 'originalinvoice.com';
      pdf.saveGraphicsState();
      pdf.setGState(new pdf.GState({ opacity: 0.15 }));
      
      const centerX = pageWidth / 2;
      const centerY = pageHeight / 2;
      pdf.text(watermarkText, centerX, centerY, {
        angle: 45,
        align: 'center',
        baseline: 'middle'
      });
      
      pdf.restoreGraphicsState();
    }
    
    pdf.setTextColor(150, 150, 150);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    const footerText = 'Generated by originalinvoice.com';
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    pdf.text(footerText, pageWidth / 2, pageHeight - 5, {
      align: 'center'
    });

    pdf.save(filename);
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF');
  }
};

/**
 * Alternative function name for compatibility
 */
export const printInvoiceAsPDF = downloadInvoiceAsPDF;
