import type { Metadata } from "next";
import "./globals.css";
import ActivityTracker from "@/components/ActivityTracker";
import { AuthProvider } from "@/contexts/AuthContext";
import i18n from "@/lib/i18ns";
import { LanguageProvider } from "@/contexts/LanguageContext";
import ErrorBoundary from "@/components/ErrorBoundary";

export const metadata: Metadata = {
    title: "Original Invoice",
    description: "Generated by create next app",
    icons: {
        icon: "/assets/header logo.svg",
    },
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@300;400;500;600;700;800;900&family=Lato:wght@300;400;500;600;700&display=swap"
                    rel="stylesheet"
                />
            </head>
            <body className="antialiased">
                <ErrorBoundary>
                    <AuthProvider>
                        <LanguageProvider>
                            <ActivityTracker />
                            {children}
                        </LanguageProvider>
                    </AuthProvider>
                </ErrorBoundary>
            </body>
        </html >
    );
}
