import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.css";

const interTight = Inter_Tight({
    subsets: ["latin"],
    variable: "--font-inter-tight",
});

export const metadata: Metadata = {
    title: "Original Invoice",
    description: "Generated by create next app",
    icons: {
        icon: "/assets/header logo.svg",
    },
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={`${interTight.className} antialiased`}>
        {children}
        </body>
        </html>
    );
}
